export const TASK_TYPE = {

    GET_LOADING : 'GET_LOADING',

    GET_ALL_TASK: 'GET_ALL_TASK',
    SUCCESS_GET_ALL_TASK: 'SUCCESS_GET_ALL_TASK',
    GET_TASK_BY_ID: 'GET_TASK_BY_ID',
    ADD_NEW_TASK: 'ADD_NEW_TASK',

    CHANGE_FILTER: 'CHANGE_FILTER',
    GET_KEY_SEARCH: 'GET_KEY_SEARCH',
    GET_CURRENT_PAGE: 'GET_CURRENT_PAGE',



  }