export const TASK_TYPE = {

    GET_LOADING : 'GET_LOADING',

    GET_ALL_TASK: 'GET_ALL_TASK',
    GET_ALL_TASK_SUCCESS: 'GET_ALL_TASK_SUCCESS',
    GET_TASK_BY_ID: 'GET_TASK_BY_ID',
    GET_TASK_BY_ID_SUCCESS: 'GET_TASK_BY_ID_SUCCESS',
    ADD_NEW_TASK: 'ADD_NEW_TASK',
    ADD_NEW_TASK_SUCCESS: 'ADD_NEW_TASK_SUCCESS',
    UPDATE_TASK: 'UPDATE_TASK',
    DELETE_TASK: 'DELETE_TASK',
    UPDATE_TASK_SUCCESS: 'UPDATE_TASK_SUCCESS',



    CHANGE_FILTER: 'CHANGE_FILTER',
    GET_KEY_SEARCH: 'GET_KEY_SEARCH',
    GET_CURRENT_PAGE: 'GET_CURRENT_PAGE',



  }